defmodule XOTPPUBKEY do
require Record
  Record.defrecord :"AttributePKCS-7", [type: :undefined, values: :undefined]
  Record.defrecord :"AlgorithmIdentifierPKSC-7", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"AlgorithmIdentifierPKCS-10", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"AttributePKCS-10", [type: :undefined, values: :undefined]
  Record.defrecord :"SubjectPublicKeyInfo-PKCS-10", [algorithm: :undefined, subjectPublicKey: :undefined]
  Record.defrecord :"ECPrivateKey", [version: :undefined, privateKey: :undefined, parameters: :asn1_NOVALUE, publicKey: :asn1_NOVALUE]
  Record.defrecord :"DSAPrivateKey", [version: :undefined, p: :undefined, q: :undefined, g: :undefined, y: :undefined, x: :undefined]
  Record.defrecord :"DHParameter", [prime: :undefined, base: :undefined, privateValueLength: :asn1_NOVALUE]
  Record.defrecord :"DigestInfoNull", [digestAlgorithm: :undefined, digest: :undefined]
  Record.defrecord :"DigestInfoPKCS-1", [digestAlgorithm: :undefined, digest: :undefined]
  Record.defrecord :"RSASSA-PSS-params", [hashAlgorithm: :undefined, maskGenAlgorithm: :undefined, saltLength: :asn1_DEFAULT, trailerField: :asn1_DEFAULT]
  Record.defrecord :"AlgorithmNull", [algorithm: :undefined, parameters: :undefined]
  Record.defrecord :"Algorithm", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"OtherPrimeInfo", [prime: :undefined, exponent: :undefined, coefficient: :undefined]
  Record.defrecord :"RSAPrivateKey", [version: :undefined, modulus: :undefined, publicExponent: :undefined, privateExponent: :undefined, prime1: :undefined, prime2: :undefined, exponent1: :undefined, exponent2: :undefined, coefficient: :undefined, otherPrimeInfos: :asn1_NOVALUE]
  Record.defrecord :"RSAPublicKey", [modulus: :undefined, publicExponent: :undefined]
  Record.defrecord :"Curve", [a: :undefined, b: :undefined, seed: :asn1_NOVALUE]
  Record.defrecord :"ECParameters", [version: :undefined, fieldID: :undefined, curve: :undefined, base: :undefined, order: :undefined, cofactor: :asn1_NOVALUE]
  Record.defrecord :"Pentanomial", [k1: :undefined, k2: :undefined, k3: :undefined]
  Record.defrecord :"Characteristic-two", [m: :undefined, basis: :undefined, parameters: :undefined]
  Record.defrecord :"ECDSA-Sig-Value", [r: :undefined, s: :undefined]
  Record.defrecord :"FieldID", [fieldType: :undefined, parameters: :undefined]
  Record.defrecord :"ValidationParms", [seed: :undefined, pgenCounter: :undefined]
  Record.defrecord :"DomainParameters", [p: :undefined, g: :undefined, q: :undefined, j: :asn1_NOVALUE, validationParms: :asn1_NOVALUE]
  Record.defrecord :"Dss-Sig-Value", [r: :undefined, s: :undefined]
  Record.defrecord :"Dss-Parms", [p: :undefined, q: :undefined, g: :undefined]
  Record.defrecord :"ACClearAttrs", [acIssuer: :undefined, acSerial: :undefined, attrs: :undefined]
  Record.defrecord :"AAControls", [pathLenConstraint: :asn1_NOVALUE, permittedAttrs: :asn1_NOVALUE, excludedAttrs: :asn1_NOVALUE, permitUnSpecified: :asn1_DEFAULT]
  Record.defrecord :"SecurityCategory", [type: :undefined, value: :undefined]
  Record.defrecord :"Clearance", [policyId: :undefined, classList: :asn1_DEFAULT, securityCategories: :asn1_NOVALUE]
  Record.defrecord :"RoleSyntax", [roleAuthority: :asn1_NOVALUE, roleName: :undefined]
  Record.defrecord :"SvceAuthInfo", [service: :undefined, ident: :undefined, authInfo: :asn1_NOVALUE]
  Record.defrecord :"IetfAttrSyntax", [policyAuthority: :asn1_NOVALUE, values: :undefined]
  Record.defrecord :"TargetCert", [targetCertificate: :undefined, targetName: :asn1_NOVALUE, certDigestInfo: :asn1_NOVALUE]
  Record.defrecord :"AttCertValidityPeriod", [notBeforeTime: :undefined, notAfterTime: :undefined]
  Record.defrecord :"IssuerSerial", [issuer: :undefined, serial: :undefined, issuerUID: :asn1_NOVALUE]
  Record.defrecord :"V2Form", [issuerName: :asn1_NOVALUE, baseCertificateID: :asn1_NOVALUE, objectDigestInfo: :asn1_NOVALUE]
  Record.defrecord :"ObjectDigestInfo", [digestedObjectType: :undefined, otherObjectTypeID: :asn1_NOVALUE, digestAlgorithm: :undefined, objectDigest: :undefined]
  Record.defrecord :"Holder", [baseCertificateID: :asn1_NOVALUE, entityName: :asn1_NOVALUE, objectDigestInfo: :asn1_NOVALUE]
  Record.defrecord :"AttributeCertificateInfo", [version: :undefined, holder: :undefined, issuer: :undefined, signature: :undefined, serialNumber: :undefined, attrCertValidityPeriod: :undefined, attributes: :undefined, issuerUniqueID: :asn1_NOVALUE, extensions: :asn1_NOVALUE]
  Record.defrecord :"AttributeCertificate", [acinfo: :undefined, signatureAlgorithm: :undefined, signatureValue: :undefined]
  Record.defrecord :"IssuingDistributionPoint", [distributionPoint: :asn1_NOVALUE, onlyContainsUserCerts: :asn1_DEFAULT, onlyContainsCACerts: :asn1_DEFAULT, onlySomeReasons: :asn1_NOVALUE, indirectCRL: :asn1_DEFAULT, onlyContainsAttributeCerts: :asn1_DEFAULT]
  Record.defrecord :"AccessDescription", [accessMethod: :undefined, accessLocation: :undefined]
  Record.defrecord :"DistributionPoint", [distributionPoint: :asn1_NOVALUE, reasons: :asn1_NOVALUE, cRLIssuer: :asn1_NOVALUE]
  Record.defrecord :"PolicyConstraints", [requireExplicitPolicy: :asn1_NOVALUE, inhibitPolicyMapping: :asn1_NOVALUE]
  Record.defrecord :"GeneralSubtree", [base: :undefined, minimum: :asn1_DEFAULT, maximum: :asn1_NOVALUE]
  Record.defrecord :"NameConstraints", [permittedSubtrees: :asn1_NOVALUE, excludedSubtrees: :asn1_NOVALUE]
  Record.defrecord :"BasicConstraints", [cA: :asn1_DEFAULT, pathLenConstraint: :asn1_NOVALUE]
  Record.defrecord :"EDIPartyName", [nameAssigner: :asn1_NOVALUE, partyName: :undefined]
  Record.defrecord :"AnotherName", ["type-id": :undefined, value: :undefined]
  Record.defrecord :"PolicyMappings_SEQOF", [issuerDomainPolicy: :undefined, subjectDomainPolicy: :undefined]
  Record.defrecord :"NoticeReference", [organization: :undefined, noticeNumbers: :undefined]
  Record.defrecord :"UserNotice", [noticeRef: :asn1_NOVALUE, explicitText: :asn1_NOVALUE]
  Record.defrecord :"PolicyQualifierInfo", [policyQualifierId: :undefined, qualifier: :undefined]
  Record.defrecord :"PolicyInformation", [policyIdentifier: :undefined, policyQualifiers: :asn1_NOVALUE]
  Record.defrecord :"PrivateKeyUsagePeriod", [notBefore: :asn1_NOVALUE, notAfter: :asn1_NOVALUE]
  Record.defrecord :"AuthorityKeyIdentifier", [keyIdentifier: :asn1_NOVALUE, authorityCertIssuer: :asn1_NOVALUE, authorityCertSerialNumber: :asn1_NOVALUE]
  Record.defrecord :"EncryptedData", [version: :undefined, encryptedContentInfo: :undefined]
  Record.defrecord :"DigestedData", [version: :undefined, digestAlgorithm: :undefined, contentInfo: :undefined, digest: :undefined]
  Record.defrecord :"SignedAndEnvelopedData", [version: :undefined, recipientInfos: :undefined, digestAlgorithms: :undefined, encryptedContentInfo: :undefined, certificates: :asn1_NOVALUE, crls: :asn1_NOVALUE, signerInfos: :undefined]
  Record.defrecord :"RecipientInfo", [version: :undefined, issuerAndSerialNumber: :undefined, keyEncryptionAlgorithm: :undefined, encryptedKey: :undefined]
  Record.defrecord :"EncryptedContentInfo", [contentType: :undefined, contentEncryptionAlgorithm: :undefined, encryptedContent: :asn1_NOVALUE]
  Record.defrecord :"EnvelopedData", [version: :undefined, recipientInfos: :undefined, encryptedContentInfo: :undefined]
  Record.defrecord :"DigestInfoPKCS-7", [digestAlgorithm: :undefined, digest: :undefined]
  Record.defrecord :"SignerInfo", [version: :undefined, issuerAndSerialNumber: :undefined, digestAlgorithm: :undefined, authenticatedAttributes: :asn1_NOVALUE, digestEncryptionAlgorithm: :undefined, encryptedDigest: :undefined, unauthenticatedAttributes: :asn1_NOVALUE]
  Record.defrecord :"SignerInfo_unauthenticatedAttributes_uaSet_SETOF", [type: :undefined, values: :undefined]
  Record.defrecord :"SignerInfo_unauthenticatedAttributes_uaSequence_SEQOF", [type: :undefined, values: :undefined]
  Record.defrecord :"SignedData", [version: :undefined, digestAlgorithms: :undefined, contentInfo: :undefined, certificates: :asn1_NOVALUE, crls: :asn1_NOVALUE, signerInfos: :undefined]
  Record.defrecord :"ContentInfo", [contentType: :undefined, content: :asn1_NOVALUE]
  Record.defrecord :"KeyEncryptionAlgorithmIdentifier", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"IssuerAndSerialNumber", [issuer: :undefined, serialNumber: :undefined]
  Record.defrecord :"DigestEncryptionAlgorithmIdentifier", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"DigestAlgorithmIdentifier", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"ContentEncryptionAlgorithmIdentifier", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"SignerInfoAuthenticatedAttributes_aaSet_SETOF", [type: :undefined, values: :undefined]
  Record.defrecord :"SignerInfoAuthenticatedAttributes_aaSequence_SEQOF", [type: :undefined, values: :undefined]
  Record.defrecord :"CertificationRequest", [certificationRequestInfo: :undefined, signatureAlgorithm: :undefined, signature: :undefined]
  Record.defrecord :"CertificationRequest_signatureAlgorithm", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"CertificationRequestInfo", [version: :undefined, subject: :undefined, subjectPKInfo: :undefined, attributes: :undefined]
  Record.defrecord :"CertificationRequestInfo_subjectPKInfo", [algorithm: :undefined, subjectPublicKey: :undefined]
  Record.defrecord :"CertificationRequestInfo_subjectPKInfo_algorithm", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"CertificationRequestInfo_attributes_SETOF", [type: :undefined, values: :undefined]
  Record.defrecord :"TeletexDomainDefinedAttribute", [type: :undefined, value: :undefined]
  Record.defrecord :"PresentationAddress", [pSelector: :asn1_NOVALUE, sSelector: :asn1_NOVALUE, tSelector: :asn1_NOVALUE, nAddresses: :undefined]
  Record.defrecord :"ExtendedNetworkAddress_e163-4-address", [number: :undefined, "sub-address": :asn1_NOVALUE]
  Record.defrecord :"PDSParameter", ["printable-string": :asn1_NOVALUE, "teletex-string": :asn1_NOVALUE]
  Record.defrecord :"UnformattedPostalAddress", ["printable-address": :asn1_NOVALUE, "teletex-string": :asn1_NOVALUE]
  Record.defrecord :"TeletexPersonalName", [surname: :undefined, "given-name": :asn1_NOVALUE, initials: :asn1_NOVALUE, "generation-qualifier": :asn1_NOVALUE]
  Record.defrecord :"ExtensionAttribute", ["extension-attribute-type": :undefined, "extension-attribute-value": :undefined]
  Record.defrecord :"BuiltInDomainDefinedAttribute", [type: :undefined, value: :undefined]
  Record.defrecord :"PersonalName", [surname: :undefined, "given-name": :asn1_NOVALUE, initials: :asn1_NOVALUE, "generation-qualifier": :asn1_NOVALUE]
  Record.defrecord :"BuiltInStandardAttributes", ["country-name": :asn1_NOVALUE, "administration-domain-name": :asn1_NOVALUE, "network-address": :asn1_NOVALUE, "terminal-identifier": :asn1_NOVALUE, "private-domain-name": :asn1_NOVALUE, "organization-name": :asn1_NOVALUE, "numeric-user-identifier": :asn1_NOVALUE, "personal-name": :asn1_NOVALUE, "organizational-unit-names": :asn1_NOVALUE]
  Record.defrecord :"ORAddress", ["built-in-standard-attributes": :undefined, "built-in-domain-defined-attributes": :asn1_NOVALUE, "extension-attributes": :asn1_NOVALUE]
  Record.defrecord :"AlgorithmIdentifier", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"TBSCertList", [version: :asn1_NOVALUE, signature: :undefined, issuer: :undefined, thisUpdate: :undefined, nextUpdate: :asn1_NOVALUE, revokedCertificates: :asn1_NOVALUE, crlExtensions: :asn1_NOVALUE]
  Record.defrecord :"TBSCertList_revokedCertificates_SEQOF", [userCertificate: :undefined, revocationDate: :undefined, crlEntryExtensions: :asn1_NOVALUE]
  Record.defrecord :"CertificateList", [tbsCertList: :undefined, signatureAlgorithm: :undefined, signature: :undefined]
  Record.defrecord :"Extension", [extnID: :undefined, critical: :asn1_DEFAULT, extnValue: :undefined]
  Record.defrecord :"SubjectPublicKeyInfo", [algorithm: :undefined, subjectPublicKey: :undefined]
  Record.defrecord :"Validity", [notBefore: :undefined, notAfter: :undefined]
  Record.defrecord :"TBSCertificate", [version: :asn1_DEFAULT, serialNumber: :undefined, signature: :undefined, issuer: :undefined, validity: :undefined, subject: :undefined, subjectPublicKeyInfo: :undefined, issuerUniqueID: :asn1_NOVALUE, subjectUniqueID: :asn1_NOVALUE, extensions: :asn1_NOVALUE]
  Record.defrecord :"Certificate", [tbsCertificate: :undefined, signatureAlgorithm: :undefined, signature: :undefined]
  Record.defrecord :"AttributeTypeAndValue", [type: :undefined, value: :undefined]
  Record.defrecord :"Attribute", [type: :undefined, values: :undefined]
  Record.defrecord :"Extension-Any", [extnID: :undefined, critical: :asn1_DEFAULT, extnValue: :undefined]
  Record.defrecord :"OTPExtension", [extnID: :undefined, critical: :asn1_DEFAULT, extnValue: :undefined]
  Record.defrecord :"OTPExtensionAttribute", [extensionAttributeType: :undefined, extensionAttributeValue: :undefined]
  Record.defrecord :"OTPCharacteristic-two", [m: :undefined, basis: :undefined, parameters: :undefined]
  Record.defrecord :"OTPFieldID", [fieldType: :undefined, parameters: :undefined]
  Record.defrecord :"PublicKeyAlgorithm", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"SignatureAlgorithm-Any", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"SignatureAlgorithm", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"OTPSubjectPublicKeyInfo-Any", [algorithm: :undefined, subjectPublicKey: :undefined]
  Record.defrecord :"OTPSubjectPublicKeyInfo", [algorithm: :undefined, subjectPublicKey: :undefined]
  Record.defrecord :"OTPOLDSubjectPublicKeyInfo", [algorithm: :undefined, subjectPublicKey: :undefined]
  Record.defrecord :"OTPOLDSubjectPublicKeyInfo_algorithm", [algo: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"OTPAttributeTypeAndValue", [type: :undefined, value: :undefined]
  Record.defrecord :"OTPTBSCertificate", [version: :asn1_DEFAULT, serialNumber: :undefined, signature: :undefined, issuer: :undefined, validity: :undefined, subject: :undefined, subjectPublicKeyInfo: :undefined, issuerUniqueID: :asn1_NOVALUE, subjectUniqueID: :asn1_NOVALUE, extensions: :asn1_NOVALUE]
  Record.defrecord :"OTPCertificate", [tbsCertificate: :undefined, signatureAlgorithm: :undefined, signature: :undefined]
end
