defmodule XPKCSFRAME do
require Record
  Record.defrecord :"AlgorithmIdentifierPKCS5v2-0", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"PKAttribute", [type: :undefined, values: :undefined, valuesWithContext: :asn1_NOVALUE]
  Record.defrecord :"PKAttribute_valuesWithContext_SETOF", [value: :undefined, contextList: :undefined]
  Record.defrecord :"AlgorithmIdentifierPKCS-8", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"RC5-CBC-Parameters", [version: :undefined, rounds: :undefined, blockSizeInBits: :undefined, iv: :asn1_NOVALUE]
  Record.defrecord :"RC2-CBC-Parameter", [rc2ParameterVersion: :asn1_NOVALUE, iv: :undefined]
  Record.defrecord :"PBMAC1-params", [keyDerivationFunc: :undefined, messageAuthScheme: :undefined]
  Record.defrecord :"PBMAC1-params_keyDerivationFunc", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"PBMAC1-params_messageAuthScheme", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"PBES2-params", [keyDerivationFunc: :undefined, encryptionScheme: :undefined]
  Record.defrecord :"PBES2-params_keyDerivationFunc", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"PBES2-params_encryptionScheme", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"PBEParameter", [salt: :undefined, iterationCount: :undefined]
  Record.defrecord :"PBKDF2-params", [salt: :undefined, iterationCount: :undefined, keyLength: :asn1_NOVALUE, prf: :asn1_DEFAULT]
  Record.defrecord :"PBKDF2-params_salt_otherSource", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"PBKDF2-params_prf", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"Context", [contextType: :undefined, contextValues: :undefined, fallback: :asn1_DEFAULT]
  Record.defrecord :"EncryptedPrivateKeyInfo", [encryptionAlgorithm: :undefined, encryptedData: :undefined]
  Record.defrecord :"EncryptedPrivateKeyInfo_encryptionAlgorithm", [algorithm: :undefined, parameters: :asn1_NOVALUE]
  Record.defrecord :"Attributes_SETOF", [type: :undefined, values: :undefined, valuesWithContext: :asn1_NOVALUE]
  Record.defrecord :"Attributes_SETOF_valuesWithContext_SETOF", [value: :undefined, contextList: :undefined]
  Record.defrecord :"PrivateKeyInfo", [version: :undefined, privateKeyAlgorithm: :undefined, privateKey: :undefined, attributes: :asn1_NOVALUE]
  Record.defrecord :"PrivateKeyInfo_privateKeyAlgorithm", [algorithm: :undefined, parameters: :asn1_NOVALUE]
end
